### PR TITLE
add option to darken past weeks

### PR DESCRIPTION
**Pull request by allibell**
Hi!  I love this tool - I just found it and printed a calendar for myself.  But since I plan to fill in the weeks as they pass, I wanted the past weeks to be filled-in.  For we-the-lazy, it seems the generate script should have an option to do this for you.

I tested this by creating a calendar without and with the new flag.  Resulting PDFs are below, respectively.
[no_flag.pdf](https://github.com/eriknyquist/generate_life_calendar/files/7629943/no_flag.pdf)
[flag.pdf](https://github.com/eriknyquist/generate_life_calendar/files/7629942/flag.pdf)

### CODE REVIEW

**Comment by sjbotha** [comment]
Thanks so much for doing this! Exactly what I was looking for. Had to look in the code to find the switch to use which is "-d" for anyone else looking. Probably should update the README.md to mention this.

**Comment by eriknyquist** [comment]
@allibell thanks for adding this, I like it!

also, sorry it took me soooo long to respond, I must have missed the email when you made this PR initially. But, @sjbotha 's comment today alerted me, I did see the email for that :)

If you're still willing to fix the conflicts, I will test it out on my end and merge it in (much quicker this time, I promise!)

**Comment by allibell** [comment]
no worries!  been there.

just fixed the conflicts and tested again.  looks good to me!  

(apologies for the force-push, I made a commit to format with `black` but realized it made a bunch of other changes irrelevant to this PR so I removed that commit.  format as you wish 🙂 )

**Comment by eriknyquist** [comment]
tested out here, looks good to me. ship it!

**Pull request merged**
